### ISSUE TITLE
home/landing page design

### ISSUE THREAD

**Issue by adilasif** [chingu-voyages/bears-project-3#7]
Any ideas or suggestions for what you want users to see when they type in our URL, please comment here!

Anything at all, from a full mockup, to elements you want to see such as a sticky header/navbar or a sidebar, or suggestions such as card-based navigation is helpful. If you particularly like the design of a website and think we can/should incorporate elements from that site, post a link or a screenshot along with a comment detailing what it is you like.

**Comment by NariRoh** [comment]
I just made a wireframe by referring to the meetup website. I think it will be easier and more detailed once we decided what features we want to have in our app :) 
Link : https://wireframe.cc/CLR9tn

**Comment by timowens9** [comment]
We should also start considering our Routes. Off the top of my head /users, /profile, /posts, etc

**Comment by adilasif** [comment]
Been trying to plan out a site map so we can know the routing. We can start with the basics though - /profile /users /posts as you say
